In [1]:
#inporting libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plyt
import seaborn as sn

In [2]:
#read csv file

df = pd.read_csv("D:/Fraud Detection model project 2/Raw_dataset/financial_fraud_detection_dataset.csv")

In [3]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent,Unnamed: 14
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0,NaN
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0,NaN
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0,NaN
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0,NaN
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         5000 non-null   str
 1   Customer_ID            5000 non-null   str
 2   Transaction_Date       5000 non-null   str
 3   Transaction_Amount     5000 non-null   float64
 4   Merchant_Category      5000 non-null   str
 5   Payment_Method         5000 non-null   str
 6   Device_Type            5000 non-null   str
 7   Location               5000 non-null   str
 8   Is_International       5000 non-null   int64
 9   Previous_Transactions  5000 non-null   int64
 10  Average_Spend          5000 non-null   float64
 11  Account_Age_Days       5000 non-null   int64
 12  Suspicious_Keyword     5000 non-null   str
 13  Fraudulent             5000 non-null   int64
 14  Unnamed: 14            0 non-null      float64
dtypes: float64(3), int64(4), str(8)
memory usage: 883.7 KB

In [5]:
df.shape

(5000, 15)

In [6]:
df.describe()

,Transaction_Amount,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Fraudulent,Unnamed: 14
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,0.0
mean,79.180664,0.088200,99.414000,258.377132,1011.158200,0.096400,NaN
std,78.964045,0.283614,57.022968,140.230639,568.633834,0.295169,NaN
min,0.000000,0.000000,1.000000,10.010000,30.000000,0.000000,NaN
25%,22.365000,0.000000,50.000000,138.772500,530.000000,0.000000,NaN
50%,55.455000,0.000000,100.000000,261.810000,1012.500000,0.000000,NaN
75%,110.297500,0.000000,148.000000,378.525000,1496.000000,0.000000,NaN
max,653.800000,1.000000,199.000000,499.990000,1999.000000,1.000000,NaN

In [8]:
df.isnull().sum()

Transaction_ID              0
Customer_ID                 0
Transaction_Date            0
Transaction_Amount          0
Merchant_Category           0
Payment_Method              0
Device_Type                 0
Location                    0
Is_International            0
Previous_Transactions       0
Average_Spend               0
Account_Age_Days            0
Suspicious_Keyword          0
Fraudulent                  0
Unnamed: 14              5000
dtype: int64